# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fee5bac8e4a726dfca2f74b21937cda6a2e644a67638f499a805d15f6b8ade7a7858c5a4a8835e02ca5f2fce2fe7fa448648bb2da97db0c0597043b712ba4538

test:
  secret_key_base: 49d39d707a4d2fc6c168786a145bf79ced24745392df398564b716c549c4e6b0eb37e41f331a455b9eca17b02ca305eb9f11724d7c2657e3396d2198fdab040b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
